---
title: "statistical learning"
author: "Kaila Boyer"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(glmnet)
library(viridis)

knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = .7,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  scale_colour_discrete = scale_colour_viridis_d,
scale_fill_discrete = scale_fill_viridis_d
)
```

## Lasso 
Prediciting birthweight 
```{r}
set.seed(11)

bwt_df = 
  read_csv("birthweight.csv") %>% 
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(frace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(mrace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4")) %>% 
  sample_n(200)
```

model.matrix - if you were trying to fit regression, here is a data frame 
```{r}
x = model.matrix(bwt ~ . , bwt_df)[,-1]
y = bwt_df$bwt
```

Let's fit lasso 
```{r}
lambda_grid <- 10^seq(3, -2, by = -0.1)

lasso_fit <- glmnet(x,y)

lasso_cv <- cv.glmnet(x, y, lambda = lambda_grid)

lambda_optimal <- lasso_cv$lambda.min
```

we can actually see what we did 

```{r}
lasso_fit %>% 
  broom::tidy() %>% 
  complete(term, lambda, fill = list(estimate = 0)) %>% 
  filter( term != "(Intercept)") %>% 
  ggplot(aes(x = log(lambda), y = estimate, color = term)) + 
  geom_path() + 
  geom_vline(xintercept = log(lambda_optimal))
  
```

## Cluster pokemons

```{r}
pokemon_df <- read_csv("pokemon.csv") %>% 
  janitor::clean_names() %>% 
  select(speed, hp)
```

look at the pokemons 
```{r}
pokemon_df %>% 
  ggplot(aes(x = hp, y = speed)) + 
  geom_point()
```

use k-means to identify clusters 

```{r}
kmeans_fit <- kmeans(x = pokemon_df, centers = 3)
```

model is the first argument in augment 
identifies what cluster it is in 
```{r}
poke_df <- pokemon_df %>% 
  broom::augment(kmeans_fit, .)

poke_df %>% 
  ggplot(aes(x = hp, y = speed, color = .cluster)) + 
  geom_point(alpha = 0.5)
```

